remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
title: [container-security site]
description: [A site about container security]
logo: "images/logo.png"
google_analytics: G-CRQ9HG0N7J
aux_links:
  "Edit on GitHub":
    - "https://github.com/raesene/container-security-site"
