remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
title: [container-security site]
description: [A site about container security]

aux_links:
  "Edit on GitHub":
    - "https://github.com/raesene/container-security-site"
